server:
  port: 8083

spring:
  application:
    name: InventoryService
  data:
    mongodb:
      uri: mongodb://localhost:27017/inventory_db
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
