server:
  port: 8085

spring:
  application:
    name: PAYMENT-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/payment_db}
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    uz.fido.payment-service: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud: DEBUG
  file:
    name: logs/payment-service.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 7
      clean-history-on-start: true
