server:
  port: 8085

spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_db

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: INFO
    com.example.paymentservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
