server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: secret-key-should-be-long-and-secure
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    uz.fido.auth-service: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/auth-service.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 7
      clean-history-on-start: true