server:
  port: 8081

spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: secret-key-should-be-long-and-secure
  expiration: 3600000 # 1 hour in milliseconds
