server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    discovery:
      enabled: true
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:your-very-long-and-secure-jwt-secret-key-for-hs256}
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    uz.fido.authservice: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
  file:
    name: logs/auth-service.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 7
      clean-history-on-start: true